user:
  id: ou
  enabled: true
  discord_webhook_key: default
stocks:
- symbol: '1815'
  average_cost: 97.85
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '2303'
  average_cost: 129.5
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '2408'
  average_cost: 206.5
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '2409'
  average_cost: 20.95
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '2421'
  average_cost: 153
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '3289'
  average_cost: 164.35
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '3587'
  average_cost: 317.36
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '3653'
  average_cost: 3265
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '3665'
  average_cost: 2013.33
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '3707'
  average_cost: 85.85
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '5269'
  average_cost: 1410
  profit_alerts:
  - 30
  - 50
  - 75
- symbol: '8046'
  average_cost: 871.8
  profit_alerts:
  - 30
  - 50
  - 75
